In [4]:
import numpy as np
from numpy import dtype

In [5]:
b = np.array([(1.5,2,3), (4,5,6), (12,11,13),(21,22,23)])

In [6]:
print b

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]
 [12.  11.  13. ]
 [21.  22.  23. ]]


Numpy array Shape

In [7]:
print b.shape

(4, 3)


In [10]:
b = np.zeros((3,4), dtype="int64")

In [11]:
print b

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
print b.shape

(3, 4)


In [9]:
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])