In [1]:
import numpy as np
from numpy import dtype


In [2]:
b = np.ones( (2,3), dtype=np.int16)    

In [3]:
print b

[[1 1 1]
 [1 1 1]]


# Multiple Dimensional Array

In [7]:
b = np.ones((3,2,2,3,4), dtype=np.int16) 

In [8]:
print b

[[[[[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]

   [[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]]


  [[[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]

   [[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]]]



 [[[[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]

   [[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]]


  [[[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]

   [[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]]]



 [[[[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]

   [[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]]


  [[[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]

   [[1 1 1 1]
    [1 1 1 1]
    [1 1 1 1]]]]]
