In [1]:
import numpy as np
from numpy import dtype

Simple Random with all funtions:

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

numpy.random.rand

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.rand.html

In [113]:
b = np.random.rand()
print b

0.377642764909


# Generate One row and two columns

In [114]:
b = np.random.randn(3,3,2)

In [17]:
print b

[[[-0.63024315 -1.41862466]
  [-1.57354843  0.41038596]
  [-0.71440485 -1.42726162]]

 [[-2.0567366  -1.49132615]
  [ 1.44896098 -1.2244771 ]
  [-1.16138751 -1.16249712]]

 [[-0.51454411 -0.52864294]
  [-0.81568505  0.24539708]
  [-0.00974528  0.15805219]]]


# Generate two row and three columns

In [18]:
b = np.random.randn(2,3)

In [19]:
print b

[[0.90159054 0.52774244 2.46805943]
 [0.80401146 0.16106474 0.67430136]]


https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.randint.html