In [4]:
import numpy as np
from numpy import dtype

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html

Gives a new shape to an array without changing its data.

In [5]:
x = np.arange(6)

In [6]:
print x

[0 1 2 3 4 5]


In [5]:
y = x.reshape((2, 3))

In [7]:
x

array([0, 1, 2, 3, 4, 5])

In [6]:
print y

[[0 1 2]
 [3 4 5]]


In [8]:
a = np.arange(6).reshape((3, 2))
print a

[[0 1]
 [2 3]
 [4 5]]


In [9]:
print np.reshape(a, (2, 3))

[[0 1 2]
 [3 4 5]]


In [16]:
a = np.array([[1,2,3], [4,5,6]])
print a

[[1 2 3]
 [4 5 6]]


In [17]:
print np.reshape(a, a.size)

[1 2 3 4 5 6]


numpy allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria

In [18]:
z = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
z.shape

(3, 4)

In [19]:
z.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Now trying to reshape with (-1, 1) . We have provided column as 1 but rows as unknown . So we get result new shape as (12, 1).again compatible with original shape(3,4)

In [20]:
z.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

New shape as (-1, 2). row unknown, column 2. we get result new shape as (6, 2)

In [21]:
z.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Now trying to keep column as unknown. New shape as (1,-1). i.e, row is 1, column unknown. we get result new shape as (1, 12)

In [22]:
z.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

New shape (2, -1). Row 2, column unknown. we get result new shape as (2,6)

In [19]:
z.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

New shape as (3, -1). Row 3, column unknown. we get result new shape as (3,4)

In [20]:
z.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

And finally, if we try to provide both dimension as unknown i.e new shape as (-1,-1). It will throw an error

In [23]:
z.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [25]:
z.shape

(3, 4)

In [27]:

z.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)