In [1]:
import numpy as np
from numpy import dtype

In [2]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [3]:
A*B

array([[2, 0],
       [0, 4]])

In [4]:
# matrix product

A.dot(B)

array([[5, 4],
       [3, 4]])

In [4]:
A

array([[1, 1],
       [0, 1]])

In [5]:
A = A*3

A

array([[3, 3],
       [0, 3]])

In [6]:
A

array([[3, 3],
       [0, 3]])

In [7]:
B

array([[2, 0],
       [3, 4]])

In [8]:
C = B + A

C

array([[5, 3],
       [3, 7]])