In [1]:
import numpy as np
from numpy import dtype

In [2]:
b = np.arange(12).reshape(3,4)

In [3]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [5]:
b.min(axis=1)     

array([0, 4, 8])