In [1]:
import numpy as np
from numpy import dtype

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[0]

0

In [5]:
a[2]

2

In [6]:
a[2:5]

array([2, 3, 4])

In [7]:
# start with 0 index till 6th index with 2 iterations

a[:6:2] = -1000 

In [8]:
a

array([-1000,     1, -1000,     3, -1000,     5,     6,     7,     8,     9])

In [9]:
# start with ist index till end with 3 iterations
a[1::3] = -2000

In [10]:
a

array([-1000, -2000, -1000,     3, -2000,     5,     6, -2000,     8,     9])

In [11]:
a = np.arange(10)

In [12]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print a[-1]
print a[-3]

9
7


In [14]:
a[-7:]

array([3, 4, 5, 6, 7, 8, 9])