In [1]:
import numpy as np
from numpy import dtype

In [2]:
b = np.arange(12).reshape(3,4)

In [3]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b[2,3]

11

In [5]:
# each row in the second column of b

print
print b[0:3, 1]


[1 5 9]


In [6]:
# all row in second column

print 
print b[ : ,1]


[1 5 9]


In [7]:
# each column in the second and third row of b

print
print b[1:3, : ]


[[ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# just the last row

print 
print b[-1]


[ 8  9 10 11]
