In [2]:
import numpy as np
from numpy import dtype

In [3]:
b = np.arange(12).reshape(3,4)

In [4]:
# iterate all rows

for row in b:
    print(row)
    
print
print b[:]

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
# iterate all rows and index column

for row in b:
    print(row[1])

1
5
9


In [7]:
# iterate all index one by one


for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
# OR (convert in array) 

print
print b.ravel()


[ 0  1  2  3  4  5  6  7  8  9 10 11]
