In [1]:
import numpy as np
from numpy import dtype

In [2]:
a = np.arange(12).reshape(3,4)
b = a > 4

In [3]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [4]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [5]:
# replace only TRUE

a[b] = 0

In [6]:
print
print a


[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]
