In [1]:
import numpy as np
a = np.arange(1, 10)

In [2]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
# compare to range:
x = range(1,10)
print(x)    # x is an iterator
print(list(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


# some more arange examples: (Float)

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html

In [4]:
# numpy.arange([start, ]stop, [step, ]dtype=None)


x = np.arange(10.4)

print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
x = np.arange(0.5, 10.4, 0.8)
print(x)

[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [6]:
x = np.arange(0.5, 10.4, 0.8, int)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
import numpy as np

x = np.arange(0, 10, 2, int)
print(x)

b = np.linspace(0, 10, 2, dtype=int)  
print(b)

[0 2 4 6 8]
[ 0 10]
