In [1]:
import numpy as np

a = np.arange(15)

In [2]:
print a


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
print
print a.shape


(3, 5)


In [6]:
print
print a.ndim


2


In [6]:
print
print a.dtype
print a.dtype.name


int64
int64



8


In [7]:
print
print a.size


15


In [8]:
print
print type(a)


<type 'numpy.ndarray'>


# class numpy.ndarray

An array object represents a multidimensional, homogeneous array of fixed-size items. An associated data-type object describes the format of each element in the array (its byte-order, how many bytes it occupies in memory, whether it is an integer, a floating point number, or something else, etc.)

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.html